server:
  servlet:
    context-path: /pauta-ms

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pauta-ms-database
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true


api:
  sessao:
    criar-sessao: "http://localhost:8081/sessao-ms/sessao/criar-sessao"
